// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjm5w5Her7Yf8uZEnmf2EpOQYi3zCUt8g',
    appId: '1:697316165791:web:446241d5a8eff764c6baaa',
    messagingSenderId: '697316165791',
    projectId: 'e-commerce-depi-fab4f',
    authDomain: 'e-commerce-depi-fab4f.firebaseapp.com',
    storageBucket: 'e-commerce-depi-fab4f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nHsO_Q9nYwMrOUq_U106CKCUGLl6idU',
    appId: '1:697316165791:android:2eceab76b810d42ec6baaa',
    messagingSenderId: '697316165791',
    projectId: 'e-commerce-depi-fab4f',
    storageBucket: 'e-commerce-depi-fab4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJKogxKfVZuPllEtssfJm5qPm5IP3j5GM',
    appId: '1:697316165791:ios:281341e8a03b4926c6baaa',
    messagingSenderId: '697316165791',
    projectId: 'e-commerce-depi-fab4f',
    storageBucket: 'e-commerce-depi-fab4f.firebasestorage.app',
    iosBundleId: 'com.example.ezbuy',
  );

  

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJKogxKfVZuPllEtssfJm5qPm5IP3j5GM',
    appId: '1:697316165791:ios:281341e8a03b4926c6baaa',
    messagingSenderId: '697316165791',
    projectId: 'e-commerce-depi-fab4f',
    storageBucket: 'e-commerce-depi-fab4f.firebasestorage.app',
    iosBundleId: 'com.example.ezbuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjm5w5Her7Yf8uZEnmf2EpOQYi3zCUt8g',
    appId: '1:697316165791:web:04ea5c6ec488de84c6baaa',
    messagingSenderId: '697316165791',
    projectId: 'e-commerce-depi-fab4f',
    authDomain: 'e-commerce-depi-fab4f.firebaseapp.com',
    storageBucket: 'e-commerce-depi-fab4f.firebasestorage.app',
  );

}